add solution for 2-module
js-tasks-ru/jsbasic-20211108_shkipercore pull request #3
Opened 2021-11-27 17:20 UTC by Shkipercore

2021-11-27 17:21 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-11-28 10:32 UTC, SinimaWath requested changes

2021-11-28 10:32 UTC, SinimaWath commented on 2-module/3-task/index.js
> +  b: '',
Так как a и b - это числа, то их значение по-умолчанию, лучше должно быть числом:
```
a: 0,
b: 0,
```

2021-11-29 08:21 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-11-29 08:21 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-11-29 08:21 UTC, Shkipercore commented on 2-module/3-task/index.js
> +  b: '',
Исправлено

2021-11-29 15:54 UTC, SinimaWath approved these changes
все круто!

2021-11-29 15:55 UTC, merged